CREATE SCHEMA WebRevistas;
USE WebRevistas;

CREATE TABLE Usuario(
  EmailUsuario VARCHAR(50) NOT NULL,
  NombreUsuario VARCHAR(45) NOT NULL,
  UsuarioSistema VARCHAR(45) NOT NULL UNIQUE,
  Password VARCHAR(45) NOT NULL,
  TipoUsuario INT NOT NULL,
  EstadoUsuario INT NULL DEFAULT 1,
  CONSTRAINT PK_USUARIO 
    PRIMARY KEY (EmailUsuario));

CREATE TABLE Perfil (
  EmailUsuario VARCHAR(50) NOT NULL,
  Foto VARCHAR(45) NOT NULL,
  Hobbies VARCHAR(60) NULL,
  TemasInteres VARCHAR(100) NULL,
  Descripcion VARCHAR(250) NULL,
  FechaNacimiento DATE NOT NULL,
  Sexo VARCHAR(12) NOT NULL,
  CONSTRAINT PK_PERFIL
    PRIMARY KEY (EmailUsuario),
  CONSTRAINT FK_USUARIO_TO_USUARIO
    FOREIGN KEY (EmailUsuario)
    REFERENCES Usuario(EmailUsuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE Categoria (
  IdCategoria INT NOT NULL AUTO_INCREMENT,
  NombreCategoria VARCHAR(45) NOT NULL,
  CONSTRAINT PK_CATEGORIA
    PRIMARY KEY (IdCategoria));

CREATE TABLE Revista (
  IdRevista INT NOT NULL AUTO_INCREMENT,
  EmailEditor VARCHAR(50) NOT NULL,
  IdCategoria INT NOT NULL,
  NombreRevista VARCHAR(50) NOT NULL,
  CuotaSuscripcion FLOAT NULL DEFAULT 0,
  CostoPorDia FLOAT NOT NULL,
  EstadoComentarios INT NULL DEFAULT 1,
  EstadoLikes INT NULL DEFAULT 1,
  EstadoSuscripciones INT NULL DEFAULT 1,
  Descripcion VARCHAR(100) NULL,
  PorcentajeAdmin FLOAT NOT NULL,
  CONSTRAINT PK_REVISTA
    PRIMARY KEY (IdRevista),
  CONSTRAINT FK_REVISTA_TO_CATEGORIA
    FOREIGN KEY (IdCategoria)
    REFERENCES Categoria(IdCategoria)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_REVISTA_TO_USUARIO
    FOREIGN KEY (EmailEditor)
    REFERENCES Usuario(EmailUsuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE ComentarioRevista (
  IdComentario INT NOT NULL AUTO_INCREMENT,
  IdRevista INT NOT NULL,
  EmailSuscriptor VARCHAR(50) NOT NULL,
  FechaComentario DATE NOT NULL,
  Comentario VARCHAR(250) NOT NULL,
  CONSTRAINT PK_COMENTARIO
    PRIMARY KEY (IdComentario),
  CONSTRAINT FK_COMENTARIO_TO_REVISTA
    FOREIGN KEY (IdRevista)
    REFERENCES Revista(IdRevista)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_COMENTARIO_TO_USUARIO
    FOREIGN KEY (EmailSuscriptor)
    REFERENCES Usuario(EmailUsuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


CREATE TABLE LikeRevista (
  IdRevista INT NOT NULL,
  EmailSuscriptor VARCHAR(50) NOT NULL,
  FechaLike DATE NOT NULL,
  CONSTRAINT PK_LIKE
    PRIMARY KEY (IdRevista, EmailSuscriptor),
  CONSTRAINT FK_LIKE_TO_REVISTA
    FOREIGN KEY (IdRevista)
    REFERENCES Revista(IdRevista)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_LIKE_TO_USUARIO
    FOREIGN KEY (EmailSuscriptor)
    REFERENCES Usuario(EmailUsuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE PublicacionRevista (
  IdPublicacion INT NOT NULL AUTO_INCREMENT,
  IdRevista INT NOT NULL,
  EdicionRevista INT NOT NULL,
  FechaPublicacion DATE NOT NULL,
  Archivo BLOB NOT NULL,
  CONSTRAINT PK_PUBLICACION
    PRIMARY KEY (IdPublicacion),
  CONSTRAINT FK_PUBLICACION_TO_REVISTA
    FOREIGN KEY (IdRevista)
    REFERENCES Revista(IdRevista)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE SuscripcionRevista (
  IdRevista INT NOT NULL,
  EmailSuscriptor VARCHAR(50) NOT NULL,
  FechaSuscripcion DATE NOT NULL,
  EstadoSuscripcion INT NULL DEFAULT 1,
  CONSTRAINT PK_SUSCRIPCION
    PRIMARY KEY (IdRevista, EmailSuscriptor),
  CONSTRAINT FK_SUSCRIPCION_TO_REVISTA
    FOREIGN KEY (IdRevista)
    REFERENCES Revista(IdRevista)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_SUSCRIPCION_TO_USUARIO
    FOREIGN KEY (EmailSuscriptor)
    REFERENCES Usuario(EmailUsuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE Etiqueta (
  IdEtiqueta INT NOT NULL AUTO_INCREMENT,
  NombreEtiqueta VARCHAR(45) NOT NULL,
  CONSTRAINT PK_ETIQUETA
    PRIMARY KEY (IdEtiqueta));

CREATE TABLE EtiquetaRevista (
  IdRevista INT NOT NULL,
  IdEtiqueta INT NOT NULL,
  CONSTRAINT PK_ETIQUETAR
    PRIMARY KEY (IdRevista, IdEtiqueta),
  CONSTRAINT FK_ETIQUETAR_TO_REVISTA
    FOREIGN KEY (IdRevista)
    REFERENCES Revista(IdRevista)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT FK_ETIQUETAR_TO_ETIQUETA
    FOREIGN KEY (IdEtiqueta)
    REFERENCES Etiqueta(IdEtiqueta)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE PagoSuscripcion (
  IdPago INT NOT NULL AUTO_INCREMENT,
  IdRevista INT NOT NULL,
  EmailSuscriptor VARCHAR(50) NOT NULL,
  Fechapago DATE NOT NULL,
  PagoSuscripcion FLOAT NOT NULL,
  PorcentajeAdmin FLOAT NOT NULL,
  CostoPorDia FLOAT NOT NULL,
  CONSTRAINT PK_PAGO
    PRIMARY KEY (IdPago),
  CONSTRAINT FK_PAGO_TO_SUSCRIPCION
    FOREIGN KEY (IdRevista , EmailSuscriptor)
    REFERENCES SuscripcionRevista(IdRevista , EmailSuscriptor)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE PreciosGlobales (
  IdCosto INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(45) NOT NULL,
  Valor FLOAT NOT NULL,
  CONSTRAINT PK_PRECIOSG
    PRIMARY KEY (IdCosto));
